version: '3.8'

services:
  db:
    image: postgres:15
    container_name: container-wschatapp
    environment:
      POSTGRES_DB: wschatappdb
      POSTGRES_USER: wsilva
      POSTGRES_PASSWORD: adminadmin
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d  # <- restaura o banco
    ports:
      - "5432:5432"

  web:
    build: .
    container_name: wschatapp-web
    command: ./entrypoint.sh
    volumes:
      - .:/app
      - ./backups:/app/backups  # Para exportar backups
    ports:
      - "8010:8000"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  postgres_data:
