# Generated by Django 4.2.7 on 2023-12-05 13:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wschatapp", "0008_alter_rede_seguido_alter_rede_seguidor_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="data_hora",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
