# Generated by Django 4.2.7 on 2023-12-05 13:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wschatapp", "0009_alter_post_data_hora"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comentario",
            name="data_hora",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
