# Generated by Django 4.2.7 on 2023-12-11 20:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("wschatapp", "0010_alter_comentario_data_hora"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rede",
            name="seguidor",
        ),
        migrations.AlterField(
            model_name="rede",
            name="seguido",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="seguido",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="rede",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="usuario",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
