# Generated by Django 4.2.7 on 2023-11-29 15:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wschatapp", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
