# Generated by Django 4.2.7 on 2023-11-29 16:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wschatapp", "0002_delete_userprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="imagem",
            field=models.ImageField(upload_to="setup/static/assets/img/"),
        ),
    ]
