# Generated by Django 4.2.7 on 2023-12-03 03:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wschatapp", "0005_usuarioinfo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usuarioinfo",
            old_name="profile_image",
            new_name="foto_perfil",
        ),
    ]
