# Generated by Django 4.2.7 on 2023-12-03 03:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wschatapp", "0006_rename_profile_image_usuarioinfo_foto_perfil"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usuarioinfo",
            old_name="user",
            new_name="usuario",
        ),
    ]
